# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: npm install
          build_command: npm build-storybook
          path: storybook-static
          checkout: false